name: action_slider
description: A slider to confirm actions and provide feedback on the success of these after subsequent loading.
version: 0.4.0
repository: https://github.com/SplashByte/action_slider

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
