name: action_slider
description: A fully customizable slider to confirm actions and provide feedback on the success. It supports different states like loading, success and failure to provide feedback to the user.
version: 0.8.0-beta.2
repository: https://github.com/splashbyte/action_slider

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - slider
  - ui
  - button
  - animation
  - widget

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dartdoc: ^8.0.13

flutter:

funding:
  - https://buymeacoffee.com/splashbyte
  - https://ko-fi.com/splashbyte

screenshots:
  - description: 'This image shows three examples of ActionSlider.'
    path: screenshots/preview.webp
